export { default as HomePage } from './home';
export { default as ProfilePage } from './profile';
export { default as UsersPage } from './users';
export { default as PatientsPage } from './participants';
export { default as PhonesPage } from './phones';
export { default as FollowupsPage } from './followups';
export { default as AnalyticsPage } from './analytics';
export { default as PeerNavigatorsPage } from './peer-navigators';
export { default as FacilitiesPage } from './facilities';
export { default as ResourcesPage } from './resources';
export { default as CountriesPage } from './countries';
export { default as ColorsPage } from './colors';
export { default as DiscussionsPage } from './discussions';
export { default as ConversationsPage } from './conversations'
export { default as NotificationsPage } from './notifications';
export { default as ForumPage } from './forum';
export { default as PostPage } from '../manage/post';
export { default as ColorPage } from '../manage/color';
export { default as CountryPage } from '../manage/country';
export { default as DiscussionPage } from '../manage/discussion';
export { default as FacilityPage } from '../manage/facility';
export { default as ResourcePage } from '../manage/resource';
export { default as UserPage } from '../manage/user';
export { default as NotificationPage } from '../manage/notification';
export { default as PhonePage } from '../manage/phone';
export { default as PhoneParticipantsPage } from '../manage/phone-participants';
export { default as LastSeenPage } from './lastseen'
export { default as ChatPage } from './chat'
export { default as PhoneConversationsPage } from './phone-conversations'